services:
  postgres:
    image: postgres:15
    restart: always
    container_name: kdl-postgres
    environment:
      POSTGRES_DB: kdl_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: kdl-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/kdl_backend
      JWT_SECRET: supersecretjwt
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: kdl-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000/api
    depends_on:
      - backend
    command: npm run dev


volumes:
  pgdata:
